### ISSUE TITLE
Windows 10, Conda-Based installation

### ISSUE THREAD

**Issue by EldrML** [tsutterley/read-GRACE-harmonics#64]
Hi there,

I am using VS Code in Windows 10, and when I run the setup.py file, I end up with the following issue regarding what looks like decoding problems? I am somewhat inexperienced with Python, so any help would be great.

```
../read-GRACE-harmonics/setup.py install
Traceback (most recent call last):
  File "..\read-GRACE-harmonics\setup.py", line 10, in <module>
    long_description = fh.read()
  File "C:\_Miniconda3\envs\gracefo\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 3118: character maps to <undefined>
```

**Comment by tsutterley** [comment]
hey @EldrML 
I think you can use miniconda to build the environment needed
```
conda env create -f .binder/environment.yml
```
I can try to spin up a windows VM if you run into trouble

**Comment by EldrML** [comment]
> hey @EldrML I think you can use miniconda to build the environment needed
> 
> ```
> conda env create -f .binder/environment.yml
> ```
> 
> I can try to spin up a windows VM if you run into trouble

It turns out that this seemed to be an encoding issue that was resolved by changing [this](https://github.com/tsutterley/read-GRACE-harmonics/blob/0b559ca63d22e93e0f786581f0274e665357e31c/setup.py#L9) line to be
```with open("README.rst", "r", encoding='utf8') as fh:```

However, in testing, I ran into another Windows-based issue: the `numpy.float128` type is not supported in windows numpy. I was able to resolve it by changing all np.float128 references in the codebase to np.longdouble and reinstalling `gravity-toolkit`

After that, I have been able to get all except 2 of the tests to pass, [this](https://github.com/tsutterley/read-GRACE-harmonics/blob/0b559ca63d22e93e0f786581f0274e665357e31c/test/test_download_and_read.py#L19) test, which I believe requires me to input my PODAAC credentials (haven't done that yet), and [this](https://github.com/tsutterley/read-GRACE-harmonics/blob/0b559ca63d22e93e0f786581f0274e665357e31c/test/test_download_and_read.py#L90) test, which I think is a similar encoding issue as the setup.py issue, but I haven't found where the encoding is going awry yet.

Thank you for your help, and I hope this helps a little bit too--windows is weird

**Comment by tsutterley** [comment]
Alright I'll try to get these things fixed! :+1:

**Comment by tsutterley** [comment]
hey @EldrML
That helped a lot. I just merged a PR with these fixes. I reworked my github actions PR workflow to add a windows build. So (at the very least) things compile on windows and can pass the same tests I run on linux and mac. Let me know if you run into any more problems. I can add more tests to make sure more things run consistently between operating systems.

**Comment by EldrML** [comment]
Happy to help! For now, I have gotten what I need (great software btw), but I will let you know if I run into any more issues in the f future.
